### ISSUE TITLE
Devtools are broken

### ISSUE THREAD

**Issue by dhoko** [MoonchildProductions/moebius#197] opened 2017-11-21 09:15 UTC
Hey, 

I have this issue with basilisk only (_it works as expected with Pale Moon_)

#### Steps to reproduce:

Open the inspector

#### Expected behavior:
I can use the JavaScript console or the inspector etc.

#### Actual behavior:
I can't cf

![screenshot from 2017-11-21 10-12-43](https://user-images.githubusercontent.com/713283/33064084-db1bd4b4-cea4-11e7-9bae-c2cd695355a1.png)

**Comment by janekptacijarabaci** [comment] 2017-11-21 15:03
Try to give a different example than:
`http://localhost:3000/login`

**Comment by Ascrod** [comment] 2017-11-21 17:54
I am also seeing this issue on Linux. (The tools appeared to work on Windows 7 x64 the last time I tried them.)

**Operating System**: System: Linux Mint 17.3 Cinnamon (64-bit)
**Basilisk Version**: 2017.11.13 (64-bit)
**Add-ons**: None
**Example URL**: Basilisk Start Page

Symptoms:
1) The Browser Console remains empty while interacting with the browser. I get no errors in the terminal when opening it or interacting with it.
2) Opening the Developer Tools or Developer Toolbar result in errors that seem to boil down to this line:
`requireHook@resource://devtools/shared/Loader.jsm:81:16`
3) Opening the Browser Toolbox, if I get anything at all, results in an empty popup and the following error:
`[Exception... "Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIFile.persistentDescriptor]"  nsresult: "0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)"  location: "JS frame :: resource://gre/modules/addons/XPIProvider.jsm -> resource://gre/modules/addons/XPIProviderUtils.js :: parseDB :: line 629"  data: no]`

I can post more detailed stack traces if necessary.

**Comment by janekptacijarabaci** [comment] 2017-11-21 18:31
Confirmed on Linux (Ubuntu 16.04):

```
console.error: 
  Message: Error creating URI (invalid URL scheme?)
  Stack:
    @undefined:NaN:NaN
requireHook@resource://devtools/shared/Loader.jsm:81:16
@resource://devtools/server/actors/root.js:11:28
requireHook@resource://devtools/shared/Loader.jsm:81:16
get@resource://devtools/shared/builtin-modules.js:152:11
createRootActor@resource://devtools/server/actors/webbrowser.js:74:3
_onConnection@resource://devtools/server/main.js:1233:24
connectPipe@resource://devtools/server/main.js:698:22
makeRemote@resource://devtools/client/framework/target.js:399:41
open/<@resource://devtools/client/framework/toolbox.js:413:13
_run@resource://devtools/shared/task.js:311:39
TaskImpl@resource://devtools/shared/task.js:273:3
asyncFunction@resource://devtools/shared/task.js:247:14
spawn@resource://devtools/shared/task.js:161:12
open@resource://devtools/client/framework/toolbox.js:392:12
DevTools.prototype.createToolbox<@resource://devtools/client/framework/devtools.js:441:11
_run@resource://devtools/shared/task.js:311:39
process@resource://gre/modules/Promise-backend.js:917:23
walkerLoop@resource://gre/modules/Promise-backend.js:801:7
scheduleWalkerLoop/<@resource://gre/modules/Promise-backend.js:737:11

Full message: TypeError: threadClient is undefined
Full stack: detachThread@resource://gre/modules/commonjs/toolkit/loader.js
-> resource://devtools/client/framework/attach-thread.js:111:3
destroy@resource://gre/modules/commonjs/toolkit/loader.js
-> resource://devtools/client/framework/toolbox.js:2318:5
DevTools.prototype.closeToolbox<@resource://gre/modules/commonjs/toolkit/loader.js
-> resource://devtools/client/framework/devtools.js:476:11
_run@resource://gre/modules/commonjs/toolkit/loader.js
-> resource://devtools/shared/task.js:311:39
_handleResultValue@resource://gre/modules/commonjs/toolkit/loader.js
-> resource://devtools/shared/task.js:392:7
_run@resource://gre/modules/commonjs/toolkit/loader.js
-> resource://devtools/shared/task.js:319:13
TaskImpl@resource://gre/modules/commonjs/toolkit/loader.js
-> resource://devtools/shared/task.js:273:3
asyncFunction@resource://gre/modules/commonjs/toolkit/loader.js
-> resource://devtools/shared/task.js:247:14
toggleToolboxCommand@resource://gre/modules/commonjs/toolkit/loader.js
-> resource://devtools/client/framework/devtools-browser.js:79:16
oncommand@resource://gre/modules/commonjs/toolkit/loader.js
-> resource://devtools/client/menus.js:52:7
```

@trav90:
You can look at it, please?

**Comment by dhoko** [comment] 2017-11-22 09:59
@janekptacijarabaci my bad i didn't add enough details.

```sh
[fenrir]:~/Téléchargements/basilisk 
$ ./basilisk --version && myOS
Moonchild Productions Basilisk 55.0.2017.11.13

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.04
Release:	17.04
Codename:	zesty
```

2sd URL https://github.com/MoonchildProductions/moebius/issues/197#issuecomment-346118942

Output console
```
$ ./basilisk 
*************************
A coding exception was thrown in a Promise resolution callback.
See https://developer.mozilla.org/Mozilla/JavaScript_code_modules/Promise.jsm/Promise

Full message: ReferenceError: CloudSync is not defined
Full stack: _promiseUpdateUI/<@chrome://browser/content/browser-syncui.js:173:1
process@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:917:23
walkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:801:7
scheduleWalkerLoop/<@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:737:11

*************************
*************************
A coding exception was thrown in a Promise resolution callback.
See https://developer.mozilla.org/Mozilla/JavaScript_code_modules/Promise.jsm/Promise

Full message: ReferenceError: CloudSync is not defined
Full stack: _promiseUpdateUI/<@chrome://browser/content/browser-syncui.js:173:1
process@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:917:23
walkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:801:7
scheduleWalkerLoop/<@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:737:11

*************************
1511344748246	browserwindow.syncui	ERROR	updateUI failed: ReferenceError: CloudSync is not defined (chrome://browser/content/browser-syncui.js:173:1) JS Stack trace: _promiseUpdateUI/<@browser-syncui.js:173:1 < process@Promise-backend.js:917:23 < walkerLoop@Promise-backend.js:801:7 < scheduleWalkerLoop/<@Promise-backend.js:737:11
console.error: 
  Message: Error creating URI (invalid URL scheme?)
  Stack:
    @undefined:NaN:NaN
requireHook@resource://devtools/shared/Loader.jsm:81:16
@resource://devtools/shared/client/main.js:11:50
requireHook@resource://devtools/shared/Loader.jsm:81:16
get@resource://devtools/shared/builtin-modules.js:152:11
makeRemote@resource://devtools/client/framework/target.js:399:7
open/<@resource://devtools/client/framework/toolbox.js:413:13
_run@resource://devtools/shared/task.js:311:39
TaskImpl@resource://devtools/shared/task.js:273:3
asyncFunction@resource://devtools/shared/task.js:247:14
spawn@resource://devtools/shared/task.js:161:12
open@resource://devtools/client/framework/toolbox.js:392:12
DevTools.prototype.createToolbox<@resource://devtools/client/framework/devtools.js:441:11
_run@resource://devtools/shared/task.js:311:39
process@resource://gre/modules/Promise-backend.js:917:23
walkerLoop@resource://gre/modules/Promise-backend.js:801:7
scheduleWalkerLoop/<@resource://gre/modules/Promise-backend.js:737:11

*************************
A coding exception was thrown in a Promise resolution callback.
See https://developer.mozilla.org/Mozilla/JavaScript_code_modules/Promise.jsm/Promise

Full message: TypeError: inspector is undefined
Full stack: inspectNode/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/client/framework/devtools-browser.js:314:11
process@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:917:23
walkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:801:7
scheduleWalkerLoop/<@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:737:11

*************************

```

**Comment by wolfbeast** [comment] 2017-12-04 08:06
Analysis walking the stack top-down:
`yield this._target.makeRemote();` (calls) -> `this._client = new DebuggerClient(DebuggerServer.connectPipe());` -> (in lazyRequireGetter) `require(module)[property]` -> (in Builtinprovider.Loader) `return require(id)` -> `const { getStack, callFunctionWithAsyncStack } = require("devtools/shared/platform/stack");` -> (in Builtinprovider.Loader) `return require(id)`

It doesn't seem like `devtools/shared/platform/stack` exists. There's `devtools/shared/platform/chrome/stack.js` and `devtools/shared/platform/content/stack.js`. Is this a bug where Mozilla broke devtools on non-e10s, perhaps, that we have to revert?

**Comment by trav90** [comment] 2017-12-04 19:31
[Bug 1287910](https://bugzilla.mozilla.org/show_bug.cgi?id=1287910) may be a potential culprit.

**Comment by JustOff** [comment] 2017-12-30 15:48
> Bug 1287910 may be a potential culprit.

I doubt this is related to the issue. It seems something fundamentally wrong with devtools in Basilisk on Linux, 'cause I get an error even trying to import Loader.jsm.

```
var { require } = Components.utils.import("resource://devtools/shared/Loader.jsm", {});
```

This works well on Windows in Scratchpad, but throws on Linux. 

And without working devtools I can't understand how to resolve the [blocklist issue](https://github.com/MoonchildProductions/moebius/issues/232), as Error console revived by @mattatobin does not help here very much :-/

**Comment by janekptacijarabaci** [comment] 2017-12-31 13:28
If it does not bother you too much, maybe it could help:
https://bugzilla.mozilla.org/show_bug.cgi?id=1373047
(https://bugzilla.mozilla.org/show_bug.cgi?id=1372901)

**Comment by Max-E** [comment] 2018-01-06 02:14
Just chiming in that I have the same problem on 64-bit Linux Mint 18.0 Sarah (corresponding to Ubuntu 16.04)

**Comment by trav90** [comment] 2018-01-29 14:04
This was caused by compiler parallelization and will be fixed in the next Linux release of Basilisk.

**Closed by trav90** 2018-01-29 14:04 UTC
Labels: Devtools, Linux
