### ISSUE TITLE
Please provide an AppImage for Linux

### ISSUE THREAD

**Issue by Chaz6** [MoonchildProductions/moebius#174] opened 2017-11-17 19:02 UTC
Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions
- Can be listed in the [AppImageHub](https://appimage.github.io/apps) central directory of available AppImages
- Can double as a self-extracting compressed archive with the `--appimage-extract` parameter

[Here is an overview](https://appimage.github.io/apps) of projects that are already distributing upstream-provided, official AppImages.

**Comment by mattatobin** [comment] 2018-01-25 08:53
This is in the same category basically as steam and windows store with a linux eq of an AppV or more properly like a python virtualenv and a sandbox.

I have no idea what the ramifications of running the browser like this are. What it means for appdata or updates especially AUS.

Also, I don't see this as our problem or responsibly.

**Comment by mattatobin** [comment] 2018-01-25 08:56
Except that if someone wants to take up the burdon.. Oversight and testing and validation needs to be done.

**Comment by KurtPfeifle** [comment] 2018-01-30 20:32
> *"Also, I don't see this as our problem or responsibly."*

Well, offering a pre-built AppImage which is capable to directly run on almost any Linux distribution released within the last 3-4 years isn't much of a 'problem' or a 'responsibility' for anybody who wants to build a thrieving FOSS project ... it's a ***boone***, not a bane for the project because it lowers the barriers to any potential new user (even developers) to give it a first spin!

**Comment by KurtPfeifle** [comment] 2018-01-30 20:36
> *"Except that if someone wants to take up the burdon."*

@mattatobin:

Does this sound like you'd be willing to accept a pull request which implemented the following features:

1. Creates a .travis.yml file to integrate with Travis CI?
1. Use Travis CI to build an AppImage for Linux upon every commit/push of code ("continuous") or tagged release?

If so, I'd volunteer to help with testing and validation.

**Comment by mattatobin** [comment] 2018-01-30 20:38
Then you do it, show us the result, and document the steps to reproduce.

**Comment by mattatobin** [comment] 2018-01-30 20:43
We don't use that continuous integration garbage.. Is there a standard way to create this without it? From CentOS 7 with our normal build environment?

**Comment by mattatobin** [comment] 2018-01-30 20:49
What about system dependences how is that handled? What about appdata? What about mar updates via AUS? Why aren't you touching on those points?

**Comment by KurtPfeifle** [comment] 2018-01-30 21:09
> *"We don't use that continuous integration garbage"*

@mattatobin:

Can you kindly explain to me, why your opinion about continuous integration culminates in calling it "garbage"?

In any case, if you don't like it (for any reason), then just enable Travis-based builds for "tagged releases" only. At this point it stops being "CI" and just becomes an automatic build for any official release, which provides the binary downloads on [your project's GitHub release page](https://github.com/MoonchildProductions/moebius/releases).

The standard way (and the most easy, since your code already is on GitHub) to build AppImages from GitHub sources via Travis CI uses an Ubuntu Trusty environment. This makes sure the resulting binaries will run on all Linux distros released after Trusty. Of course, once this works, it can be ported to a different (also non-TravisCI) build environment and be translated into a bash *build.sh* script or a Makefile.

System dependencies will be handled as they are for all AppImages:

* embed all those into the AppImage which CANNOT reasonably expected to be present on most target Linux platforms;
* rely for the other dependencies to be provided by the target platform where the AppImage is run.

> *"What about appdata? What about mar updates via AUS? Why aren't you touching on those points?"*

Why are you shooting these questions already NOW? Look, you've been offered help. You can always turn it down once it proofs to not match your expectations. Just give it a chance, give it some time...

**Comment by TheAssassin** [comment] 2018-01-30 21:31
@mattatobin are you actually interested in shipping your software to end users? If so, how would you do it for Linux? I think we all agree packaging can be a burden sometimes (and of course takes some time), but AppImages are actually a quite comfortable way to package software, due to the awesome tools developed around the AppImage project. And, in my opinion, if you just publish source code, and don't provide binaries, there's little to no chance to reach end users. Telling people to "just compile" the software isn't really anything the average user can do. Since the 2000s, developers started to provide builds for their users in order to get some audience, until e.g., distributions can take over packaging (but that doesn't mean that this packaging is superior to binaries published by the developers). You can only understand that really when you start to think like such an end user, or by talking to end users, like @Chaz6 or @KurtPfeifle.

By the way, just because services like Travis CI obviously carry the term "continuous integration" in their name, they can be used for much more than integration tests. And you don't have to run builds there for every commit either. But let's avoid focusing on semantics.

Anyway, there's a lot of projects which just publish their AppImages on their websites. Building AppImages doesn't mean you _have to_ use CI services, you're not limited to any kind of service. @KurtPfeifle just wanted to express that many other developers see such automatic builds as an advantage in various ways. In general, one can say, AppImages are just a relatively easy way to build usable application bundles for end users. That simplicity in the design is actually the reason they can be used for so many other scenarios, that's why people combine this technology with other ones making their lives easier.

By the way, what exactly do you refer to as AUS (I'm pretty sure it's not the Australian country you're referring to)? You're requesting a statement on this, but it doesn't really get clear what it is all about. And yeah, I have to agree to @KurtPfeifle, this question seems a bit premature. I'd say, before making decisions or raising concerns, you should check out how AppImages work, and if they might work for your project.

If you agree, I could imagine @KurtPfeifle and @Chaz6 might build an AppImage for the project, which you can then inspect and base your decision on.

**Comment by KurtPfeifle** [comment] 2018-01-30 22:06
@TheAssassin:

I guess @mattatobin intended to write that one word upper-cased as *"What about MAR updates via AUS?"*, where

* ***MAR:*** is the *Mozilla ARchive* format used by their update system to deliver update packages
* ***AUS:*** stands for Mozilla's *Application Update Service*

@mattatobin:

To be honest, currently I have no clue how to answer that question of yours. However, AppImages have a mechanism of its own to almost seamlessly update any AppImage on a system. It has two tools, *AppImageUpdate* (GUI) and *appimageupdatetool* (CLI), which internally use *[zsync2](https://github.com/AppImage/zsync2)* to download binary deltas and patch the present (old) AppImage with these blocks which are different in a newly released AppImage. This saves bandwidth and time for the end user and for the file hoster. The user doesn't even have to remember where exactly she did retrieve the original AppImage from (because zsync2 will retrieve the update location from a string embedded in the old AppImage). Possibly this can be "married" with AUS, or stand side-by-side with AUS to serve AppImage updates -- but this is for a later investigation/decision.

However, this is all not yet important for now -- let's first get ready an AppImage *AT ALL* for general testing...

**Comment by wolfbeast** [comment] 2018-01-30 22:54
All right, my take on this...

Advantages:
- Less of a wild west since we can provide official, tested binaries built with in-tree libs and deps of known type and version
- Easier "first adoption"

Disadvantages:
- IIUC Requires Travis CI -- this doesn't work because it will require an external build server with sufficient resources which Travis CI services in general do not provide to FOSS. Our source tree is too big @ 24M lines of code and takes too much resources and compile time.
- Even if not using that kind of system it requires a build controlled by the AppImage tools -- that will likely clash with our own build tools. Is there a Firefox AppImage? If so, who created it and how? Can we draw on that prior work?
- Requires a separate updating mechanism that is not an OS-integrated package manager, nor compatible with our internal updater.
- On Linux we still depend on certain system libraries; this isn't necessarily compatible across the board which is why a good number of distributions have a source-build package in their package manager, making the package compile on the target system. It's unclear how an AppImage will use these system libraries, because you're making assumptions about "what is reasonably expected to be present". With our recent issues with glibc, for example, one can assume that that would be present on all systems, yet 2.26 would break the browser. How would you handle that?

As for AppData, I'm pretty sure that isn't important since it'll just go in `~/moonchild productions` and has nothing to do with the actual application binaries.

**Comment by KurtPfeifle** [comment] 2018-01-30 23:01
> *"I have no idea what the ramifications of running the browser like this are. "*

@mattatobin:

Here is a Linux build of another browser, BeakerBrowser, which runs pretty well as an AppImage:

* https://github.com/beakerbrowser/beaker/releases

(though this one -- which is based on Chromium and Electron -- does not yet implement the recommended AppImageUpdate mechanism.)

**Comment by TheAssassin** [comment] 2018-01-30 23:17
> IIUC Requires Travis CI -- this doesn't work because it will require an external build server with sufficient resources which Travis CI services in general do not provide to FOSS. Our source tree is too big @ 24M lines of code and takes too much resources and compile time.

That's absolutely not true, as I explained in my post. You can package AppImages on Travis. But the tools are in no way bound to Travis CI. For example, I code all my AppImage build scripts as normal shell scripts and run them locally to test them. You can just do the same for your app, and build them where ever you like. Just make sure the system is "sufficiently old" to maximize compatibility (some projects still use CentOS 6, but @mattatobin mentioned you have a CentOS 7 infrastructure, which should work, too.

> Even if not using that kind of system it requires a build controlled by the AppImage tools -- that will likely clash with our own build tools. 

Using the AppImage tools is only the last step. You need to have the final binaries ready and working. Then, you can use tools like [linuxdeployqt](https://github.com/probonopd/linuxdeployqt) (linuxdeployqt = written in Qt, can bundle any library for any software), which analyzes that binary, and puts all dependent libraries into the so-called AppDir. This AppDir can be generated with your build tools using `make install DESTDIR=appdir` or some similar command. Then, as a last step, you use appimagetool to convert that AppDir to a real AppImage. I don't know why you guys think there'd be any kind of conflicts. Maybe someone's misunderstood the concept?

> Is there a Firefox AppImage? If so, who created it and how? Can we draw on that prior work?

There is a so-called "example AppImage", one that is made by the AppImage team for demo purposes only, and not meant to be used in real life. This AppImage is basically just created from the static builds Mozilla provide, which already contain all the libraries. So I'd say, it's not really useful, as it won't demonstrate a build from source.

Instead, I'd like you to check out the [linuxdeploy README](https://github.com/probonopd/linuxdeployqt#using-linuxdeployqt-with-travis-ci)'s section on using it with Travis CI. Please, just look there, it's just an example, just ignore the fact it's for Travis, you can still learn the basic steps to get a working AppImage from it.

> Requires a separate updating mechanism that is not an OS-integrated package manager, nor compatible with our internal updater.

I don't think any kind of OS integrated package manager has _any_ relevance in this discussion. No other distribution system has a relation to them, be it a tarball, or an AppImage.

Also, AppImages don't _require_ another updater, but there's a standardized, relatively simple to set up and low maintenance *optional* update mechanism. Nobody said that was the only way. Making such claims is just a bit disruptive.

> On Linux we still depend on certain system libraries; this isn't necessarily compatible across the board which is why a good number of distributions have a source-build package in their package manager, making the package compile on the target system. It's unclear how an AppImage will use these system libraries, because you're making assumptions about "what is reasonably expected to be present". With our recent issues with glibc, for example, one can assume that that would be present on all systems, yet 2.26 would break the browser. How would you handle that?

That's what I meant about "sufficiently old build environment". All the system libraries you mention are backwards compatible. They are not bundled on purpose. Generally, if a system has been released _after_ your build environment, the AppImages will be compatible. The AppImage project even maintains a list of binaries which don't need to be or should not be bundled [here](https://github.com/AppImage/AppImages/blob/master/excludelist). There's nothing unclear about it. This method has proven in the real world to work fine, and compatibility issues are rare. The AppImage claim that AppImages work on nearly any Linux distro have been confirmed by several famous developers shipping AppImages.

All these things are easy to look up. I am a bit disappointed that I had to write such a long text to clarify some misunderstandings. Also, I dislike this attitude you established, which is made up of being concerned about problems while none of these have occurred yet. I can only encourage you to try some existing AppImages and build one as a base for future discussions. You'll see that most of your concerns are nothing big to worry about.

If you need further assistance or want to ask more detailed questions, you may also visit #AppImage on Freenode, where you will meet a lot of AppImage users, developers, packagers, etc., which can give replies to your questions, too. I hope you understand that as a developer, I probably won't get to answering any more detailed questions here as they have been answered in other places already. Our community in #AppImage is willing to help with any kind of problem.

**Comment by mattatobin** [comment] 2018-01-31 00:07
And this is why we don't do this.. It has, as expected, gone from a simple request and a simple set of questions into a bunch of added steps we would need to take.

Tell me this, can KDE be shipped as an AppImage. Or more importantly, has someone shipped a universal Firefox build as an AppImage?

Cause we are talking about a highly complex piece of software that is more than just a random utility or graphics editor.

Until someone can provide an example of Pale Moon as an AppImage that can run on any distro flawlessly and can provide CLEAR and DIRECT instructions to reproduce it without Travis.. Then I think my recommendation is to reject this as an additional releng burden and a fad that will fade out like every other attempt to create universal linux packages.

**Comment by wolfbeast** [comment] 2018-01-31 00:38
> Also, I dislike this attitude you established, which is made up of being concerned about problems while none of these have occurred yet.

So, because I ask a few pointed questions that require explanation, and because I am NOT a Linux person and trying to wrap my brain around how these system libraries work with portable Linux apps, I suddenly have an "attitude"? Great approach you have there. {/sarcasm}

If these tools can be used standalone on a complete binary, then I don't understand why all documentation of these appimages I have seen so far require some form of CI or other build integration process, fetching from remote URLS, and more of that -- it also doesn't list how to make sure required libs are, in fact, included in the image and not used from the system it's run on. If it's a matter of a little bit of extra RelEng then it's not a big deal, but that doesn't seem to be the case.

**Comment by probonopd** [comment] 2018-01-31 17:34
> Tell me this, can KDE be shipped as an AppImage.

Complex KDE apps, yes. Krita and Kdevelop, for example.

> Or more importantly, has someone shipped a universal Firefox build as an AppImage?

Yes. I have made an example one. https://bintray.com/probono/AppImages/Firefox#files/

**Comment by probonopd** [comment] 2018-01-31 17:40
> because I am NOT a Linux person and trying to wrap my brain around how these system libraries work with portable Linux apps

Actually that makes you a great target user of AppImage - it's made for people like you, to make your life _easier_ because instead of compiling for different distributions you just can do one AppImage and be done with it.

> If these tools can be used standalone on a complete binary, then I don't understand why all documentation of these appimages I have seen so far require some form of CI or other build integration process, fetching from remote URLS, and more of that

Because that way, your builds are a) automatic on each git push and b) reproducible, i.e., others can easily reproduce the exact builds you are doing c) using a service like Travis CI you do not need infrastructure such as own build servers.

But if you want to do builds on a developer's local notebook - you can absolutely go ahead and just do that.

> it also doesn't list how to make sure required libs are, in fact, included in the image and not used from the system it's run on

You need to bundle those libraries that you don't want to be taken from the system inside the AppImage. Tools like `linuxdeployqt` can automate this for you.

> If it's a matter of a little bit of extra RelEng then it's not a big deal, but that doesn't seem to be the case.

Depends. I have made working builds in as little time as 5 minutes, by literally copying the example from https://github.com/probonopd/linuxdeployqt#using-linuxdeployqt-with-travis-ci and customizing a few lines in it. That is if the software in question can be built on Ubuntu 14.04 trusty.

**Comment by trav90** [comment] 2018-01-31 18:03
My thoughts:

1) We already have build infrastructure (me), so I don't see the need for a CI service.

2) I keep seeing references to building AppImages in Ubuntu 14.04 (both here and other places on the net) in order to produce binaries compatible with most other distros, but I already have a working build environment using CentOS 7 that produces binaries that run on most if not all distros that are not EOL.

3) How is marking a file to be executable easier than extracting a tarball? In my experience, most people who use Linux come from a Windows background and are familiar with extracting and then running the appropriate extracted file. Not all Linux users are familiar with marking a file as an executable before they can run it.

I can see where some would have an appeal for AppImages and maybe I'm just being dense, but I am failing to see any real advantages here to what we (I) already have/do.

**Comment by probonopd** [comment] 2018-01-31 18:08
> We already have build infrastructure (me), so I don't see the need for a CI service.

Then you can use that. Only we can't send you a PR for making the AppImages because we can't replicate that exact infrastructure easily.

> I keep seeing references to building AppImages in Ubuntu 14.04 (both here and other places on the net) in order to produce binaries compatible with most other distros, but I already have a working build environment using CentOS 7 that produces binaries that run on most if not all distros that are not EOL.

Then you can use that.

> How is marking a file to be executable easier than extracting a tarball? 

It takes additional time and space. Imagine a 10 GB file (e.g., game).

> Not all Linux users are familiar with marking a file as an executable before they can run it.

Then we need to educate them ;-)

![](https://discourse-cdn-sjc2.com/standard12/uploads/appimage/optimized/1X/a4889c5cb8711d6845b58135080787d2f370af35_1_500x500.gif)

**Comment by TheAssassin** [comment] 2018-01-31 18:12
I hate repeating myself:

>> IIUC Requires Travis CI -- this doesn't work because it will require an external build server with sufficient resources which Travis CI services in general do not provide to FOSS. Our source tree is too big @ 24M lines of code and takes too much resources and compile time.
>
> That's absolutely not true, as I explained in my post. You can package AppImages on Travis. But the tools are in no way bound to Travis CI. For example, I code all my AppImage build scripts as normal shell scripts and run them locally to test them. You can just do the same for your app, and build them where ever you like. Just make sure the system is "sufficiently old" to maximize compatibility (some projects still use CentOS 6, but @mattatobin mentioned you have a CentOS 7 infrastructure, which should work, too.
>
> source: https://github.com/MoonchildProductions/moebius/issues/174#issuecomment-361767813

**Comment by KurtPfeifle** [comment] 2018-01-31 21:06
@trav90 wrote:

> *"We already have build infrastructure (me), so I don't see the need for a CI service."*

Searching for a site where I can download a PaleMoon binary turned out to not be quite straightforward.

***Builds for CentOS, Redhat, Fedora, openSUSE, ...? None found.***

In the end I discovered ***builds for Debian and Ubuntu*** -- on an openSUSE site: https://software.opensuse.org/download.html?project=home:stevenpusser&package=palemoon

This lets me suspect that these packages may have been built using SUSE's *Open Build Service* (OBS). Is that correct?

In any case, this gives me the opportunity to point to the fact that ***OBS has full support to build AppImages from sources***, with all dependencies (and to automatically build freshly, should any component or dependency have experienced an update). A non-Travis CI service, if you like...

The website where the general PaleMoon build process is described for various distros for these users who want to build themselves looks rather patchy to me:

* https://developer.palemoon.org/Developer_Guide:Build_Instructions/Pale_Moon/Linux

However -- no instructions, only "TODOs" for Fedora, Debian, Manjaro, Arch, ...

I appreciate your persistence to overcome all the obstacles in building binaries and documenting the process for all kinds of distros, even if you do not seem to have fully succeeded yet.

**Comment by KurtPfeifle** [comment] 2018-01-31 21:22
It's really a big pity that this site:

* http://www.palemoon.org/

describes PaleMoon as "OpenSource" within its first six words of text, but yet seems to offer the only binary build for the non-Free closed source system MS Windows. A "portable version" is offered for Windows too -- however, the portable AppImage for multiple Linux distributions isn't a thing which seems to be easily embraced by the PaleMoon stewards...

**Comment by LewJasio** [comment] 2018-01-31 22:08
There is a link on the Pale Moon homepage that points to [http://linux.palemoon.org/](http://linux.palemoon.org/). Official Linux binaries can be downloaded from there.

Builds for Debian and Ubuntu are created by another developer, and IIRC OBS is indeed used for that.

**Comment by KurtPfeifle** [comment] 2018-01-31 22:32
@LewJasio:

Now I see it!
Thanks for the hint.  👍 

I followed the link(s) to the build(s) by other developer(s), because these appear much more prominent on the page: they are in a list which in itself is already a bit exposed. The "official Linux binaries" you mentioned are not flagged as such, but somehow buried in the middle of a text paragraph behind the words *"bzipped tarball"* and can be easily overlooked when the eyes were already focusing on the list...

I see that the page also mentions a *pminstaller tool*... Experienced users used to install from Tarballs, RPMs and DEBs will easily not go with that one first, because they will not recognize it as something they are looking for. 

In order to really play out well, this page should be heavily optimized. It should guide users first and firmly to the preferred installation method (preferred by the PaleMoon developers -- is this the tarball or is this that "pminstaller tool"??) and only mention the other methods at second place.

**Comment by mattatobin** [comment] 2018-01-31 22:34
Ok.. Guys.. Listen.

Pale Moon is a highly complex piece of technology that doesn't run on every distribution perfectly in its generic form.

How does AppImage solve these issues for Arch, Slack, Gentoo, Debian? Can AppImage include every dependency and each of its dependencies into the AppImage because that is what it will take to get anywhere near a UNIVERSAL package we can ship out.

How is an AppImage created? What tools are involved.. You say Travis (program) without the CI part.. but does that mean Travis (the program) has to manage the build? How is that superior than just.. BUILDING. What is the step by step procedure on CentOS 7 that will take us from a setup Can build Pale Moon Environment to Can produce AppImage.

Why do users have to make things executable.. Not all DEs provide that option in a context menu..

What about updates to the software? What about stuff we CANNOT bundle like ffmpeg?

Stop being cryptic and satisfy these questions.

**Comment by LewJasio** [comment] 2018-01-31 22:45
@KurtPfeifle 
No problem ;).

**Comment by wolfbeast** [comment] 2018-02-02 16:30
For being self-proclaimed enthusiasts, I find it at the very least curious that you seem to have problems:
* Navigating a website menu that has clear links to all flavors of Pale Moon [1]
* Finding the source code page in said menu [2]
* Using the big-ass green download button front and center on the index page to go to the linux site to download binaries (since that is what it does if you go to the site from Linux)

Also, my developer-side questions and lack of Linux expertise has nothing to do with user-side usability thresholds and how those two would even be related -- I'm asked to CREATE the image, not USE it.

![webmenu1](https://user-images.githubusercontent.com/3359132/35743732-563cd6b4-0836-11e8-92a2-533bad5235ab.png)
![linuxdownload](https://user-images.githubusercontent.com/3359132/35743737-5b61229e-0836-11e8-9277-e07d9bbac4bc.png)

**Comment by KurtPfeifle** [comment] 2018-02-02 23:26
> *"we're asked to CREATE the image, not USE it."*

Yes -- but *you've also been offered help in that*, and you've been asked *if you are interested enough to accept a pull request* if that PR would implement the automatic creation of a Pale Moon AppImage via Travis CI.

From various responses from your camp -- like *"CI is garbage"* or *"we don't do that"* or asking unrelated questions like *"can KDE be shipped as an AppImage?"* and *"more importantly, has someone shipped a universal Firefox build as an AppImage?"* -- and ignoring all other explanations about how AppImages can be built without Travis CI -- I now conclude that at the current point in time you are not very much interested.

Hence I'll focus on other stuff for now, but I still may re-visit the topic in some weeks and try to build an AppImage as *"someone taking up the burdon"* in order to *"provide an example of Pale Moon as an AppImage that can run on any distro flawlessly"*. But... since Pale Moon is such a *"highly complex piece of software/technology"* as we were repeatedly told, I may of course also fail and silently give up and NOT ask again for your help....

----

<sup>BTW, regarding the remark that AppImage could be *"a fad that will fade out like every other attempt to create universal linux packages"*: as long as Linus Torvalds' own end-user GUI application, the *[SubSurface Dive Log](https://subsurface-divelog.org/)* software continues to use AppImage, and as long as Linus continues to say that "[This is just very cool](https://plus.google.com/+LinusTorvalds/posts/WyrATKUnmrS)" I'm not particularly discouraged by all your dismissive comments...</sup>

**Closed** 2018-02-03 00:50 UTC
Labels: Linux, Release Engineering, Wontfix

**Comment by mattatobin** [comment] 2018-02-03 00:51
k

**Comment by wolfbeast** [comment] 2018-02-06 08:39
> if you are interested enough to accept a pull request if that PR would implement the automatic creation of a Pale Moon AppImage via Travis CI.

In case it wasn't clear enough, although the reasons were stated a bit crudely: **no we're not interested in any PR that involves Travis CI.**

In addition, considering an AppImage would be packaging system libs with our mixed-licensed application, there's even the question to be asked: can this be done, legally? After all, our license statement in the application would not be listing the 3rd party licenses from the libs included in the AppImage, and its nature is a "black box" otherwise for the end user. That would make it a grey area at the very least. it's fine if you're publishing a GPL tool with GPL libs, but our browser isn't that simple.

All in all there are way too many unanswered questions here that need to be addressed before considering this kind of approach, no matter how "cool" Linus thinks it is (and I agree it is a cool idea, but not something you can just wallpaper on any application).
